### ISSUE TITLE
css设置宽高比例固定的容器

### ISSUE THREAD

**Issue by l1nyanm1ng** [l1nyanm1ng/deneb#2]
有些情况下需要固定宽度，获得一张正方形的图片，或者是显示16比9的图片，直接写死img标签的width和height固然能做到，用js动态控制也能做到，但是如果能够直接用css设置岂不美哉。

通过将div标签的margin和padding属性在垂直方向上可以设置成百分比值，由于这个百分比是相对于width计算的，在将容器的height设置为0，基于这个特性，我们可以仅设置容器的宽度，而高度就是相对于宽度的比例，这样就获得了根据宽度随动的比例固定的容器了。

容器内的内容此时无法正确获取父容器的width和height，这里需要将容器内子元素设置`position: abosolute;`将父容器设置`position: relative;`这样子元素就可以正确的获取到父容器的宽高了。

```css
.container {
  width: 100%;
  height: 0;
  padding-bottom: 100%;
  position: relative;
  background-color: tomato;
}

.content {
  position: absolute;
  width: 100%;
  height: 30%;
  background-color: cornflowerblue;
}
```

```html
<div style="width: 30%;">
  <div class="container">
    <div class="content"></div>
  </div>
</div>
```

<img width="323" alt="image" src="https://user-images.githubusercontent.com/38402334/77945549-6710e000-72f3-11ea-8c50-f1d28375967c.png">

这里可以看出子元素的高度的确是父容器的30%，这样，一个宽度随动的正方形容器我们就做好了。

同理，要获得一个16比9的容器，只需要将父容器的`padding-bottom`修改为`calc(100% * 9 / 16)`即可。

```css
.container {
  width: 100%;
  height: 0;
  padding-bottom: calc(100% * 9 / 16);
  position: relative;
  background-color: tomato;
}

.content {
  position: absolute;
  width: 100%;
  height: 30%;
  background-color: cornflowerblue;
}
```

<img width="282" alt="image" src="https://user-images.githubusercontent.com/38402334/77945796-d25ab200-72f3-11ea-80be-2070244c1526.png">
